### ISSUE TITLE
helper_functions

### ISSUE THREAD

**Issue by sleiss** [tom-doerr/commonroad_batch_processing#1]
Hey,

first of all, thanks for you work!
Sadly, I get an error when executing the notebook:
`ModuleNotFoundError: No module named 'helper_functions'`

Where can I find the helper_functions?

Thanks!

**Comment by tom-doerr** [comment]
Is it possible that you are using an older version of commonroad-search?
There was an update a few days back, so you might need to do a `git pull`.
In the newest version there is a `helper_functions.py` in the directory `commonroad-search/notebooks/batch_processing/script`, so if you move the notebook to that directory before executing it, it should work.

**Comment by sleiss** [comment]
Thanks, pulling the latest changes from the upstream repo solved the issue!
